name: Build

on:
  push:
    branch: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Build kernel
      id: build
      run: |
        docker run --rm --volume $(pwd):/work barrenechea/android-build-env:latest /bin/bash -c "\
        cd / &&\
        git clone https://github.com/SebastianBar/Kirisakura_OP7Pro_A11 work &&\
        cd /work &&\
        ./build_kirisakura_debian.sh"

    - name: List all files within out folder
      run: ls -alG out/arch/arm64/boot
      if: always()

    - uses: actions/upload-artifact@v2
      with:
        name: kirisakura-kernel
        path: zipper/kirisakura-kernel.zip
